export const REGISTER_USER = "REGISTER_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

export const REGISTER_RESERVATION = "REGISTER_RESERVATION";
